In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.16.1'

In [3]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [4]:
a=tf.constant(10)
a

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [5]:
a=tf.constant(10.5)
a

<tf.Tensor: shape=(), dtype=float32, numpy=10.5>

In [6]:
c= tf.constant("prtaeek")
c

<tf.Tensor: shape=(), dtype=string, numpy=b'prtaeek'>

In [7]:
a=tf.Variable(5)
a

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=5>

In [8]:
a=tf.Variable([1,2,3,4])
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

In [9]:
a.name
a.shape
a.dtype

tf.int32

In [10]:
a.assign([4,6,8,2])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([4, 6, 8, 2])>

In [13]:
a.assign([45,6.5,8.3,2.4])

TypeError: Cannot convert [45, 6.5, 8.3, 2.4] to EagerTensor of dtype int32