In [1]:
import tensorflow as tf
import numpy as np

In [ ]:
#ADDITION

In [2]:
a =10
b=20
tf.add(a,b) # can be used for adding in list, tuple , numpy array,

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [5]:
l1= [1,2,3,4]
a= 10
tf.add(l1,a) # also works with numpy array adddition, tf cona]satnt and scalar , variable, variable with scalar

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([11, 12, 13, 14])>

In [ ]:
#SUBTRACTION

In [4]:
tf.subtract(b,a)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [6]:
tf.subtract(a,l1) # can be used for adding in list, tuple , numpy array,also works with numpy array adddition, tf cona]satnt and scalar , variable, variable with scalar

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([9, 8, 7, 6])>

In [ ]:
#MULTIPLICATION

In [3]:
a=10
b=20
tf.multiply(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=200>

In [4]:
a*b

200

In [7]:
tf.multiply(a,l1) # can be used for adding in list, tuple , numpy array,also works with numpy array adddition, tf cona]satnt and scalar , variable, variable with scalar

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 20, 30, 40])>

In [ ]:
#DIVISION

In [9]:
a=2
b=[10,20,30,40,50]
tf.divide(b,a) # array with array works, numpy array with scalar, numpy array with single array , tensor with scalar, 2 variable , numpy array with different shape

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([ 5., 10., 15., 20., 25.])>