In [16]:
#SQUARE ROOT 

In [15]:
import numpy as np
import tensorflow as tf

In [7]:
a=9.0


In [9]:
tf.sqrt(a)

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [13]:
la=[13,14,.0,15]

In [14]:
tf.sqrt(la)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([3.6055512, 3.7416575, 0.       , 3.8729835], dtype=float32)>

In [17]:
npa=([2,3,4,5.0])
tf.sqrt(npa)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.4142135, 1.7320508, 2.       , 2.236068 ], dtype=float32)>

In [18]:
npa.dtype

AttributeError: 'list' object has no attribute 'dtype'

In [21]:
yp= np.ones(6).reshape(2,1,3,1)*4
yp

array([[[[4.],
         [4.],
         [4.]]],


       [[[4.],
         [4.],
         [4.]]]])

In [22]:
tf.sqrt(yp)

<tf.Tensor: shape=(2, 1, 3, 1), dtype=float64, numpy=
array([[[[2.],
         [2.],
         [2.]]],


       [[[2.],
         [2.],
         [2.]]]])>

In [23]:
#SQRT OF TF CONSTANT TENSOR
tf_ct1=tf.constant([4,9,16], dtype='float')
tf.sqrt(tf_ct1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

In [ ]:
#POWER 

In [26]:
tf.pow(3,2) # numpy,tesor, constant, tensortf, variable

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [28]:
tf.maximum(4,5)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [29]:
a=[56,46,34]
b=[53,76,89]
tf.maximum(a,b) # tuple, with scalar, list with scalar,numpy with scalar2 tf constant tensor, tf constant with scalarr, 

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([56, 76, 89])>

In [30]:
tf.minimum(a,b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([53, 46, 34])>