In [1]:
import tensorflow as tf

In [4]:
x=tf.ones((2,2), tf.float32)
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [5]:
ones_3d=tf.ones((2,2,4), tf.float32)
ones_3d

<tf.Tensor: shape=(2, 2, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [6]:
const_2d= tf.constant([[1,2,3],[4,5,6]])
const_2d

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [7]:
tf.ones_like(const_2d)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]])>

In [11]:
def ones_variable(shape,dtype, initializer):
    return tf.variable(initializer(shape=shape, dtype=dtype))

In [12]:
ones_variable((2,2),tf.float32, tf.ones_initializer())

AttributeError: module 'tensorflow' has no attribute 'variable'