In [1]:
import tensorflow as tf

In [3]:
st1=tf.SparseTensor(indices=[[0,3],[2,4]] , values=[10,20] , dense_shape=[3,10])
st1

SparseTensor(indices=tf.Tensor(
[[0 3]
 [2 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([10 20], shape=(2,), dtype=int32), dense_shape=tf.Tensor([ 3 10], shape=(2,), dtype=int64))

In [4]:
import numpy as np

In [8]:
np_array= np.array([[1,0,0,0],
                   [0,0,0,0],
                   [0,0,4,0],
                   [1,0,0,2]])
np_array

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 4, 0],
       [1, 0, 0, 2]])

In [11]:
st2= tf.sparse.from_dense(np_array)
st2

SparseTensor(indices=tf.Tensor(
[[0 0]
 [2 2]
 [3 0]
 [3 3]], shape=(4, 2), dtype=int64), values=tf.Tensor([1 4 1 2], shape=(4,), dtype=int32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))

In [14]:
st2.values.numpy().tolist()

[1, 4, 1, 2]

In [16]:
st2.indices.numpy().tolist()

[[0, 0], [2, 2], [3, 0], [3, 3]]

#SPARSE TO DENSE

In [18]:
tf.sparse.to_dense(st2)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 4, 0],
       [1, 0, 0, 2]])>

In [20]:
st_add=tf.sparse.add(st2, st2)
st_add

SparseTensor(indices=tf.Tensor(
[[0 0]
 [2 2]
 [3 0]
 [3 3]], shape=(4, 2), dtype=int64), values=tf.Tensor([2 8 2 4], shape=(4,), dtype=int32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))

In [22]:
tf.sparse.to_dense(st_add).numpy()

array([[2, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 8, 0],
       [2, 0, 0, 4]])