In [3]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [10]:
zeros2d= tf.zeros((2,2), dtype=tf.int32)
zeros2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]])>

In [13]:
zeros3d.dtype
zeros3d.shape
zeros3d.numpy()

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [15]:
z=tf.constant([[1,2,3],[4,5,6]])
z

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [17]:
zeros_like= tf.zeros_like(z, dtype=tf.bool)
zeros_like

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[False, False, False],
       [False, False, False]])>

In [23]:
def zeros_variable(shape, dtype,intializer):
    return tf.variable(initializer(shape=shape,dtype=dtype))

In [24]:
zerostf= zeros_variable((2,2), tf.float32,tf.zeros_initializer())
zerostf

AttributeError: module 'tensorflow' has no attribute 'variable'